In [1]:
from scipy.special import lambertw
import numpy as np

In [12]:
a = np.array([1,2,3,4])
b = np.array([0.0,0.0,1,0.0])
c = a * b
c[c!=0]

np.arange(4) * b

array([0., 0., 2., 0.])

In [2]:
w = 2345678
x = lambertw(w)
print(x)
print(x * np.exp(x))

(12.169178630483948+0j)
(2345677.9999999986+0j)


In [5]:
(1 + x / np.infty) ** np.infty

/tmp/ipykernel_13379/2147157968.py:1: RuntimeWarning: invalid value encountered in cdouble_scalars
  (1 + x / np.infty) ** np.infty


(nan+nanj)

In [1]:
from DataLoader.DataLoader import YahooFinanceDataLoader

In [2]:
data = YahooFinanceDataLoader('BTC-USD', split_point='2018-01-01', load_from_file=True)

In [8]:
np.array(data.data_train.close)

array([  457.334015,   424.440002,   394.79599 , ..., 14656.200195,
       12952.200195, 14156.400391])

In [ ]:
np.e

In [ ]:
np.power(1 + 1/np.infty, np.infty)

In [3]:
import numpy as np
from scipy.optimize import *

In [8]:
phi = 2
k = 100

def func(z):
    return (phi - 1) / (z[0] - 1) - np.power(1 + z[0]/k, k) 

In [17]:
init_guess = np.random.rand() * 100
sol = least_squares(func, init_guess, bounds=([0, np.infty]))

In [21]:
sol

 active_mask: array([0])
        cost: 1.3445377710491652e-23
         fun: array([5.1856297e-12])
        grad: array([-8.43009607e-11])
         jac: array([[-16.25664876]])
     message: '`gtol` termination condition is satisfied.'
        nfev: 8
        njev: 8
  optimality: 8.430096067571422e-11
      status: 1
     success: True
           x: array([1.28023884])

In [18]:
init_guess

3.369428792847462

In [20]:
x = sol.x
func(x)

5.185629703419181e-12

In [ ]:
guess = np.random.randn()

In [ ]:
z = fsolve(func, guess)[0]

In [ ]:
z

In [ ]:
func(z)

In [6]:
from main import RPP
import numpy as np

In [7]:
rpp = RPP(np.infty, 1, 100)

/home/mehran/PycharmProjects/pythonProject/main.py:37: RuntimeWarning: invalid value encountered in power
  f[0] = (self.phi - 1) / (x - 1) - np.power(1 + x / self.k, self.k)
/home/mehran/PycharmProjects/pythonProject/main.py:37: ComplexWarning: Casting complex values to real discards the imaginary part
  f[0] = (self.phi - 1) / (x - 1) - np.power(1 + x / self.k, self.k)


AssertionError: Couldn't find a good solution for r*!

In [4]:
rpp.r_star

NameError: name 'rpp' is not defined

In [ ]:
rpp.s_star

In [ ]:
rpp.r_star_func(np.array([rpp.r_star]))

In [ ]:
rpp.s_star_func(np.array([rpp.s_star]))

In [8]:
k = 100
r_star = 3.74
s_star = -7.12
phi = 110.09

In [9]:
(1 - 1 / phi) / (1 - 1 / s_star) - np.power(1 + 1 / (s_star * k), k)

6.504896099546187e-07

In [4]:
fsolve??

In [22]:
least_squares??

In [1]:
a = [1, 2,3,4,5]

In [3]:
b = [2,3,4,5,6]

In [8]:
import numpy as np
np.array(b[1:]) - np.array(a[:-1])

array([2, 2, 2, 2])

In [10]:
a[1:]

[2, 3, 4, 5]